# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/4_account_painel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 600)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("background-color: #498f97;\n"
"\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.deposito_back = QtWidgets.QPushButton(self.centralwidget)
        self.deposito_back.setGeometry(QtCore.QRect(50, 230, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.deposito_back.setFont(font)
        self.deposito_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deposito_back.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: #7cbec6;\n"
"    color: #fff;\n"
"    border-radius: 75px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(140, 214, 223);\n"
"    border: 10px groove rgb(140, 214, 223);\n"
"}")
        self.deposito_back.setText("")
        icon = QtGui.QIcon.fromTheme("icones/to_left.png")
        self.deposito_back.setIcon(icon)
        self.deposito_back.setObjectName("deposito_back")
        self.extrato_back = QtWidgets.QPushButton(self.centralwidget)
        self.extrato_back.setGeometry(QtCore.QRect(630, 230, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.extrato_back.setFont(font)
        self.extrato_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.extrato_back.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: #7cbec6;\n"
"    color: #fff;\n"
"    border-radius: 75px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(140, 214, 223);\n"
"    border: 10px groove rgb(140, 214, 223);\n"
"}")
        self.extrato_back.setText("")
        self.extrato_back.setObjectName("extrato_back")
        self.transferencia_back = QtWidgets.QPushButton(self.centralwidget)
        self.transferencia_back.setGeometry(QtCore.QRect(440, 230, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.transferencia_back.setFont(font)
        self.transferencia_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transferencia_back.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: #7cbec6;\n"
"    color: #fff;\n"
"    border-radius: 75px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(140, 214, 223);\n"
"    border: 10px groove rgb(140, 214, 223);\n"
"}")
        self.transferencia_back.setText("")
        self.transferencia_back.setObjectName("transferencia_back")
        self.saque_back = QtWidgets.QPushButton(self.centralwidget)
        self.saque_back.setGeometry(QtCore.QRect(245, 230, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.saque_back.setFont(font)
        self.saque_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saque_back.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: #7cbec6;\n"
"    color: #fff;\n"
"    border-radius: 75px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(140, 214, 223);\n"
"    border: 10px groove rgb(140, 214, 223);\n"
"}")
        self.saque_back.setText("")
        self.saque_back.setObjectName("saque_back")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 0, 72, 19))
        self.label.setText("")
        self.label.setObjectName("label")
        self.saldo = QtWidgets.QLineEdit(self.centralwidget)
        self.saldo.setGeometry(QtCore.QRect(458, 65, 291, 61))
        self.saldo.setStyleSheet("background-color: #fff;\n"
"border-radius: 5px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.saldo.setText("")
        self.saldo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.saldo.setDragEnabled(False)
        self.saldo.setReadOnly(True)
        self.saldo.setObjectName("saldo")
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(310, 460, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_sair.setFont(font)
        self.btn_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sair.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    color: #fff;\n"
"    border-radius: 10px;\n"
"    background-color: #13747d;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(86, 132, 137);\n"
"    border: 1px solid #7cbec6 ;\n"
"}")
        self.btn_sair.setObjectName("btn_sair")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(8, 150, 790, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(630, 130, 121, 20))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("background-color: #498f97;\n"
"color: white;")
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.tipo = QtWidgets.QLabel(self.centralwidget)
        self.tipo.setGeometry(QtCore.QRect(58, 55, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tipo.setFont(font)
        self.tipo.setStyleSheet("color: #fff;")
        self.tipo.setText("")
        self.tipo.setAlignment(QtCore.Qt.AlignCenter)
        self.tipo.setObjectName("tipo")
        self.numero = QtWidgets.QLabel(self.centralwidget)
        self.numero.setGeometry(QtCore.QRect(58, 95, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numero.setFont(font)
        self.numero.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.numero.setStyleSheet("color: #fff;")
        self.numero.setText("")
        self.numero.setAlignment(QtCore.Qt.AlignCenter)
        self.numero.setObjectName("numero")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(333, 15, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #7cbec6;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.img_transf = QtWidgets.QLabel(self.centralwidget)
        self.img_transf.setGeometry(QtCore.QRect(490, 320, 50, 50))
        self.img_transf.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(191, 64, 64, 0)")
        self.img_transf.setText("")
        self.img_transf.setObjectName("img_transf")
        self.deposito = QtWidgets.QPushButton(self.centralwidget)
        self.deposito.setGeometry(QtCore.QRect(50, 230, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.deposito.setFont(font)
        self.deposito.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deposito.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: rgba(200, 200, 200, 0);\n"
"\n"
"    border-radius: 75px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 10px groove rgb(140, 214, 223);\n"
"}")
        self.deposito.setObjectName("deposito")
        self.img_extrato = QtWidgets.QLabel(self.centralwidget)
        self.img_extrato.setGeometry(QtCore.QRect(680, 320, 50, 50))
        self.img_extrato.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"border-radius:20px")
        self.img_extrato.setText("")
        self.img_extrato.setObjectName("img_extrato")
        self.img_saque = QtWidgets.QLabel(self.centralwidget)
        self.img_saque.setGeometry(QtCore.QRect(295, 320, 50, 50))
        self.img_saque.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(191, 64, 64, 0)")
        self.img_saque.setText("")
        self.img_saque.setObjectName("img_saque")
        self.img_dep = QtWidgets.QLabel(self.centralwidget)
        self.img_dep.setGeometry(QtCore.QRect(100, 320, 50, 50))
        self.img_dep.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(191, 64, 64, 0)")
        self.img_dep.setText("")
        self.img_dep.setObjectName("img_dep")
        self.saque = QtWidgets.QPushButton(self.centralwidget)
        self.saque.setGeometry(QtCore.QRect(245, 230, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.saque.setFont(font)
        self.saque.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saque.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: rgba(200, 200, 200, 0);\n"
"\n"
"    border-radius: 75px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 10px groove rgb(140, 214, 223);\n"
"}")
        self.saque.setObjectName("saque")
        self.transferencia = QtWidgets.QPushButton(self.centralwidget)
        self.transferencia.setGeometry(QtCore.QRect(440, 230, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.transferencia.setFont(font)
        self.transferencia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transferencia.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: rgba(200, 200, 200, 0);\n"
"\n"
"    border-radius: 75px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 10px groove rgb(140, 214, 223);\n"
"}")
        self.transferencia.setObjectName("transferencia")
        self.extrato = QtWidgets.QPushButton(self.centralwidget)
        self.extrato.setGeometry(QtCore.QRect(630, 230, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.extrato.setFont(font)
        self.extrato.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.extrato.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: rgba(200, 200, 200, 0);\n"
"\n"
"    border-radius: 75px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 10px groove rgb(140, 214, 223);\n"
"}")
        self.extrato.setObjectName("extrato")
        self.deposito_back.raise_()
        self.extrato_back.raise_()
        self.transferencia_back.raise_()
        self.saque_back.raise_()
        self.label.raise_()
        self.saldo.raise_()
        self.btn_sair.raise_()
        self.line.raise_()
        self.checkBox.raise_()
        self.tipo.raise_()
        self.numero.raise_()
        self.label_2.raise_()
        self.img_transf.raise_()
        self.img_extrato.raise_()
        self.img_saque.raise_()
        self.img_dep.raise_()
        self.transferencia.raise_()
        self.deposito.raise_()
        self.saque.raise_()
        self.extrato.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contas"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.checkBox.setText(_translate("MainWindow", "mostrar saldo"))
        self.label_2.setText(_translate("MainWindow", "Beast Bank"))
        self.deposito.setText(_translate("MainWindow", "Depósito"))
        self.saque.setText(_translate("MainWindow", "Saque"))
        self.transferencia.setText(_translate("MainWindow", "Transferência"))
        self.extrato.setText(_translate("MainWindow", "Extrato"))
